# Generated by Django 4.2.16 on 2024-12-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabletime',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
