# Generated by Django 4.2.16 on 2024-12-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_availabletime_is_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='category',
            field=models.CharField(choices=[('Asian', 'Asian Food'), ('Italian', 'Italian Food'), ('Mexican', 'Mexican Food'), ('American', 'American Food'), ('French', 'French Food')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
